# Setting overrides for the CDB helm chart at:
# https://github.com/cockroachdb/helm-charts/tree/master/cockroachdb
resources:
   requests:
     cpu: 100m
     memory: 512Mi
storage:
  persistentVolume:
    enabled: true
    size: 100Mi
tls:
  enabled: false